### ISSUE TITLE
[EPIC] Prepare database credential status manager for release

### ISSUE THREAD

**Issue by kezike** [digitalcredentials/credential-status-manager-db#2]
Tasks:
- [x] `issuer-coordinator` - pending PR review: https://github.com/digitalcredentials/issuer-coordinator/pull/17
- [x] `credential-status-manager-db` - pending PR merge and npm deployment and depending on `vc`, `vc-bitstring-status-list`, and `security-document-loader` branch dependencies (we will keep these branch dependencies for now): https://github.com/digitalcredentials/credential-status-manager-db/pull/1
- [x] `credential-status-manager-db` - allocate status positions randomly (reserved for a future release)
- [x] `credential-status-manager-git` - pending PR review and depending on `vc`, `vc-bitstring-status-list`, and `security-document-loader` branch dependencies (we will keep these branch dependencies for now): https://github.com/digitalcredentials/credential-status-manager-git/pull/24
- [x] `status-service-db` - pending PR review: https://github.com/digitalcredentials/status-service-db/pull/2
- [x] `learner-credential-wallet` - pending testing and PR re-review: https://github.com/digitalcredentials/learner-credential-wallet/pull/609
- [x] `dcc-admin-dashboard` - pending PR creation: https://github.com/orgs/digitalcredentials/projects/14/views/1?pane=issue&itemId=64143847
- [x] `workflow-coordinator` - pending PR review: https://github.com/digitalcredentials/workflow-coordinator/pull/14
- [x] `signing-service` - pending PR review - https://github.com/digitalcredentials/signing-service/pull/30
- [x] `vc-data-model` - merged and published to npm
- [x] `vc` - pending PR review and depending on `jsonld-signatures`: https://github.com/digitalcredentials/vc/pull/21
- [x] `vc-bistring-status-list` - pending PR review - https://github.com/digitalcredentials/vc-bitstring-status-list/pull/1 and depending on `vc`
- [x] `security-document-loader` - pending PR creation for patch package and npm deployment, pending `http-client` update or alternative solution, and depending on `http-client` - https://github.com/digitalcredentials/security-document-loader/issues/15
- [x] `jsonld-signatures` - published as npm `v10.1.0`
- [x] `http-client` - (Dmitri working on a patch for this: #15) potentially pending web compatibility update - https://github.com/digitalbazaar/http-client/issues/45
- [x] `web-verifier-plus` - pending `http-client` update or alternative solution and depending on `security-document-loader` and `http-client`: Dmitri working on it: https://github.com/digitalcredentials/security-document-loader/issues/15
--> This issue takes precedence over https://github.com/digitalbazaar/http-client/issues/45

**Comment by alexfigtree** [comment]
James currently working on: https://github.com/digitalcredentials/ops/issues/26

**Comment by alexfigtree** [comment]
6/10/24: Web verifier plus consensus: Drop support for OBV3 VC's in V+ that was included in this PR: https://github.com/digitalcredentials/vc/pull/13 --> and proceed with upgrade to VC 2.0

**Comment by alexfigtree** [comment]
Status manager working locally with VC2, updating services in progress

**Comment by alexfigtree** [comment]
@jchartrand Recommends moving status-service-git - pending PR review (essentially the same changes as status-service-db): https://github.com/digitalcredentials/status-service-git/pull/7 out of epic

**Comment by alexfigtree** [comment]
Items completed, moving to Release Ready

**Comment by alexfigtree** [comment]
@kezike Good to close, thanks for your help!
